apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sre-app
  labels:
    app: sre-app
spec:
  replicas: 1
  strategy:
    canary:
      analysis:
        templates:
          - templateName: sre-app-success-rate
      steps:
        - setWeight: 20
        - pause: { duration: 60s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sre-app
          image: sre-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://observability-tempo.monitoring.svc.cluster.local:4317"
            - name: ERROR_RATE
              value: "0"
            - name: LATENCY_MS
              value: "50"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
