apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
  labels:
    app: sre-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
      annotations:
        # Scrape metrics natively from the app
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sre-app
          image: sre-app:v1 # Local image loaded via 'kind load'
          imagePullPolicy: IfNotPresent # Critical for Kind local images
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://observability-tempo.monitoring.svc.cluster.local:4317"
            - name: ERROR_RATE
              value: "0" # Start with 0 errors
            - name: LATENCY_MS
              value: "50" # 50ms simulated latency
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
