apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-demo
spec:
  replicas: 1
  strategy:
    canary:
      # Run analysis in background while rollout progresses
      # analysis:
      #   templates:
      #     - clusterTemplateName: success-rate-global
      #   args:
      #     - name: service-name
      #       value: web-demo
      #     - name: namespace
      #       valueFrom:
      #         fieldRef:
      #           fieldPath: metadata.namespace
      steps:
        - setWeight: 20
        - pause: { duration: 60s } # Wait 1m for metrics/chaos
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
